[package]
name = "maketrees"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "maketrees"
crate-type = ["cdylib"]

[dependencies]
pyo3 = ">=0.28.3"
tskit = { version=">=0.15.0", features = ["derive"] }
serde = "*"
serde_json = "*"
tskit2tskit = { version = "0.1.0-alpha.0", path = "../.."}
