on:
  push:
    branches: [main, dev]
  pull_request:

name: Python data round trips

jobs:
  test-metadata:
    name: Test Python metadata round trips
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        rust:
          - stable
        python: [ "3.14" ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2.8.2
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          version: "latest"
          python-version: "3.14d"
      - name: Install tskit-python
        run: |
          uv pip install tskit
      - name: Run tests
        run: |
          # We need to make sure that tests link to the python debug runtime lib
          LD_LIBRARY_PATH=$(dirname "$(realpath "$(uv python find)")")/../lib uv run -p 3.14d cargo test

