on:
  push:
    branches: [main, dev]
  pull_request:

name: Python data round trips

jobs:
  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04]
        rust:
          - stable
        python: [ "3.14" ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2.8.2
      - uses: taiki-e/install-action@cargo-hack
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          version: "latest"
          python-version: "3.14d"
      - name: Install tskit-python
        run: |
          uv pip install "tskit>=1"
      - name: Run tests
        run: |
          # We need to make sure that tests link to the python debug runtime lib
          LD_LIBRARY_PATH=$(dirname "$(realpath "$(uv python find)")")/../lib uv run -p 3.14d cargo hack test --feature-powerset --all-targets
      - name: Run doc tests
        run: |
          # We need to make sure that tests link to the python debug runtime lib
          LD_LIBRARY_PATH=$(dirname "$(realpath "$(uv python find)")")/../lib uv run -p 3.14d cargo hack test --feature-powerset --doc
      - name: Build and run haploid_wright_fisher example
        run: |
          LD_LIBRARY_PATH=$(dirname "$(realpath "$(uv python find)")")/../lib uv run cargo run --example haploid_wright_fisher 42 10 100 5 example.trees
          rm -f example.trees
      - name: Validate build for MSRV
        run: |
          cargo hack check --all-targets --feature-powerset --rust-version
      - name: cargo doc
        run: |
          cargo doc --all-features

  clippy:
    name: clippy!!
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: Swatinem/rust-cache@v2.8.2
      - uses: taiki-e/install-action@cargo-hack
      - name: update toolchain
        run: rustup toolchain install
      - name: clippy (all targets, feature powerset)
        run: cargo hack clippy --all-targets --feature-powerset -- -D warnings

  fmt:
    name: rust fmt
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - run: |
         rustfmt --check
